name: 自动关闭过期议题

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次

jobs:
  close_stale_issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: '此议题已30天无更新，将被自动关闭。如需继续讨论，请回复此议题。'
          close-issue-message: '由于长时间无活动，此议题已被自动关闭。'
