name: Merge JSONs in /净化

on:
  push:
    paths:
      - '净化/**/*.json'
      - '!净化/合集/jh.json'

jobs:
  merge_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Merge JSON files to one big array
        run: |
          mkdir -p 净化/合集
          # 查找所有json文件，排除jh.json，然后合并为一个大数组
          files=$(find 净化 -type f -name '*.json' ! -path '净化/合集/jh.json')
          echo "[" > 净化/合集/jh.json
          first_file=1
          for file in $files; do
            # 跳过空文件
            if [ ! -s "$file" ]; then
              continue
            fi
            # 去掉首尾[ ]，避免嵌套
            content=$(cat "$file" | sed -e '1d' -e '$d')
            # 跳过空内容
            if [ -z "$content" ]; then
              continue
            fi
            if [ $first_file -eq 1 ]; then
              echo "$content" >> 净化/合集/jh.json
              first_file=0
            else
              echo "," >> 净化/合集/jh.json
              echo "$content" >> 净化/合集/jh.json
            fi
          done
          echo "]" >> 净化/合集/jh.json

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          if ! git diff --quiet 净化/合集/jh.json; then
            git add 净化/合集/jh.json
            git commit -m '自动合并净化目录下所有json文件到合集/jh.json'
            git push
          fi
