name: Merge 净化下 JSON 文件

on:
  push:
    paths:
      - '净化/*.json'
      - '!净化/合集/jh.json'
  workflow_dispatch:

jobs:
  merge-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Merge JSON files
        run: |
          mkdir -p "净化/合集"
          json_files=$(find 净化 -type f -name '*.json' ! -name 'jh.json')
          if [ -n "$json_files" ]; then
            jq -s 'add' $json_files > "净化/合集/jh.json"
          else
            echo "[]" > "净化/合集/jh.json"
          fi

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '自动合并净化目录下JSON文件为jh.json'
          file_pattern: '净化/合集/jh.json'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: '41898282+github-actions[bot]@users.noreply.github.com'