name: Merge 净化 JSON

on:
  push:
    paths:
      - '净化/**/*.json'
      - '!净化/合集/jh.json'

jobs:
  merge-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge all JSON files
        run: |
          mkdir -p 净化/合集
          files=$(find 净化 -type f -name '*.json' ! -path '净化/合集/jh.json')
          if [ -z "$files" ]; then
            echo "[]" > 净化/合集/jh.json
          else
            jq -s 'add' $files > 净化/合集/jh.json
          fi

      - name: Check if jh.json changed
        id: diff
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git add 净化/合集/jh.json
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changed
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "自动提交合集" 净化/合集/jh.json
          git push
